// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var reflection = reflection || {};

/**
 * @enum
 */
reflection.BaseType = {
  None: 0,
  UType: 1,
  Bool: 2,
  Byte: 3,
  UByte: 4,
  Short: 5,
  UShort: 6,
  Int: 7,
  UInt: 8,
  Long: 9,
  ULong: 10,
  Float: 11,
  Double: 12,
  String: 13,
  Vector: 14,
  Obj: 15,
  Union: 16
};

/**
 * @constructor
 */
reflection.Type = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.Type}
 */
reflection.Type.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.Type=} obj
 * @returns {reflection.Type}
 */
reflection.Type.getRootAsType = function(bb, obj) {
  return (obj || new reflection.Type).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {reflection.BaseType}
 */
reflection.Type.prototype.baseType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {reflection.BaseType} */ (this.bb.readInt8(this.bb_pos + offset)) : reflection.BaseType.None;
};

/**
 * @returns {reflection.BaseType}
 */
reflection.Type.prototype.element = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {reflection.BaseType} */ (this.bb.readInt8(this.bb_pos + offset)) : reflection.BaseType.None;
};

/**
 * @returns {number}
 */
reflection.Type.prototype.index = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : -1;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.Type.startType = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {reflection.BaseType} baseType
 */
reflection.Type.addBaseType = function(builder, baseType) {
  builder.addFieldInt8(0, baseType, reflection.BaseType.None);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {reflection.BaseType} element
 */
reflection.Type.addElement = function(builder, element) {
  builder.addFieldInt8(1, element, reflection.BaseType.None);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} index
 */
reflection.Type.addIndex = function(builder, index) {
  builder.addFieldInt32(2, index, -1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.Type.endType = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
reflection.KeyValue = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.KeyValue}
 */
reflection.KeyValue.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.KeyValue=} obj
 * @returns {reflection.KeyValue}
 */
reflection.KeyValue.getRootAsKeyValue = function(bb, obj) {
  return (obj || new reflection.KeyValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.KeyValue.prototype.key = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.KeyValue.prototype.value = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.KeyValue.startKeyValue = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 */
reflection.KeyValue.addKey = function(builder, keyOffset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
reflection.KeyValue.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(1, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.KeyValue.endKeyValue = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // key
  return offset;
};

/**
 * @constructor
 */
reflection.EnumVal = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.EnumVal}
 */
reflection.EnumVal.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.EnumVal=} obj
 * @returns {reflection.EnumVal}
 */
reflection.EnumVal.getRootAsEnumVal = function(bb, obj) {
  return (obj || new reflection.EnumVal).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.EnumVal.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
reflection.EnumVal.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {reflection.Object=} obj
 * @returns {reflection.Object|null}
 */
reflection.EnumVal.prototype.object = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new reflection.Object).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {reflection.Type=} obj
 * @returns {reflection.Type|null}
 */
reflection.EnumVal.prototype.unionType = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new reflection.Type).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.EnumVal.startEnumVal = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
reflection.EnumVal.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
reflection.EnumVal.addValue = function(builder, value) {
  builder.addFieldInt64(1, value, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectOffset
 */
reflection.EnumVal.addObject = function(builder, objectOffset) {
  builder.addFieldOffset(2, objectOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} unionTypeOffset
 */
reflection.EnumVal.addUnionType = function(builder, unionTypeOffset) {
  builder.addFieldOffset(3, unionTypeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.EnumVal.endEnumVal = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  return offset;
};

/**
 * @constructor
 */
reflection.Enum = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.Enum}
 */
reflection.Enum.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.Enum=} obj
 * @returns {reflection.Enum}
 */
reflection.Enum.getRootAsEnum = function(bb, obj) {
  return (obj || new reflection.Enum).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.Enum.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {reflection.EnumVal=} obj
 * @returns {reflection.EnumVal}
 */
reflection.Enum.prototype.values = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new reflection.EnumVal).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Enum.prototype.valuesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
reflection.Enum.prototype.isUnion = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {reflection.Type=} obj
 * @returns {reflection.Type|null}
 */
reflection.Enum.prototype.underlyingType = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new reflection.Type).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {reflection.KeyValue=} obj
 * @returns {reflection.KeyValue}
 */
reflection.Enum.prototype.attributes = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new reflection.KeyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Enum.prototype.attributesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
reflection.Enum.prototype.documentation = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
reflection.Enum.prototype.documentationLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.Enum.startEnum = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
reflection.Enum.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valuesOffset
 */
reflection.Enum.addValues = function(builder, valuesOffset) {
  builder.addFieldOffset(1, valuesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Enum.createValuesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Enum.startValuesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isUnion
 */
reflection.Enum.addIsUnion = function(builder, isUnion) {
  builder.addFieldInt8(2, +isUnion, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} underlyingTypeOffset
 */
reflection.Enum.addUnderlyingType = function(builder, underlyingTypeOffset) {
  builder.addFieldOffset(3, underlyingTypeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributesOffset
 */
reflection.Enum.addAttributes = function(builder, attributesOffset) {
  builder.addFieldOffset(4, attributesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Enum.createAttributesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Enum.startAttributesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} documentationOffset
 */
reflection.Enum.addDocumentation = function(builder, documentationOffset) {
  builder.addFieldOffset(5, documentationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Enum.createDocumentationVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Enum.startDocumentationVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.Enum.endEnum = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  builder.requiredField(offset, 6); // values
  builder.requiredField(offset, 10); // underlying_type
  return offset;
};

/**
 * @constructor
 */
reflection.Field = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.Field}
 */
reflection.Field.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.Field=} obj
 * @returns {reflection.Field}
 */
reflection.Field.getRootAsField = function(bb, obj) {
  return (obj || new reflection.Field).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.Field.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {reflection.Type=} obj
 * @returns {reflection.Type|null}
 */
reflection.Field.prototype.type = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new reflection.Type).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Field.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
reflection.Field.prototype.offset = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
reflection.Field.prototype.defaultInteger = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
reflection.Field.prototype.defaultReal = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {boolean}
 */
reflection.Field.prototype.deprecated = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
reflection.Field.prototype.required = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
reflection.Field.prototype.key = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {number} index
 * @param {reflection.KeyValue=} obj
 * @returns {reflection.KeyValue}
 */
reflection.Field.prototype.attributes = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? (obj || new reflection.KeyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Field.prototype.attributesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
reflection.Field.prototype.documentation = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
reflection.Field.prototype.documentationLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.Field.startField = function(builder) {
  builder.startObject(11);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
reflection.Field.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
reflection.Field.addType = function(builder, typeOffset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
reflection.Field.addId = function(builder, id) {
  builder.addFieldInt16(2, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} offset
 */
reflection.Field.addOffset = function(builder, offset) {
  builder.addFieldInt16(3, offset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} defaultInteger
 */
reflection.Field.addDefaultInteger = function(builder, defaultInteger) {
  builder.addFieldInt64(4, defaultInteger, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} defaultReal
 */
reflection.Field.addDefaultReal = function(builder, defaultReal) {
  builder.addFieldFloat64(5, defaultReal, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} deprecated
 */
reflection.Field.addDeprecated = function(builder, deprecated) {
  builder.addFieldInt8(6, +deprecated, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} required
 */
reflection.Field.addRequired = function(builder, required) {
  builder.addFieldInt8(7, +required, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} key
 */
reflection.Field.addKey = function(builder, key) {
  builder.addFieldInt8(8, +key, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributesOffset
 */
reflection.Field.addAttributes = function(builder, attributesOffset) {
  builder.addFieldOffset(9, attributesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Field.createAttributesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Field.startAttributesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} documentationOffset
 */
reflection.Field.addDocumentation = function(builder, documentationOffset) {
  builder.addFieldOffset(10, documentationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Field.createDocumentationVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Field.startDocumentationVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.Field.endField = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  builder.requiredField(offset, 6); // type
  return offset;
};

/**
 * @constructor
 */
reflection.Object = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.Object}
 */
reflection.Object.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.Object=} obj
 * @returns {reflection.Object}
 */
reflection.Object.getRootAsObject = function(bb, obj) {
  return (obj || new reflection.Object).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.Object.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {reflection.Field=} obj
 * @returns {reflection.Field}
 */
reflection.Object.prototype.fields = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new reflection.Field).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Object.prototype.fieldsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
reflection.Object.prototype.isStruct = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {number}
 */
reflection.Object.prototype.minalign = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
reflection.Object.prototype.bytesize = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {reflection.KeyValue=} obj
 * @returns {reflection.KeyValue}
 */
reflection.Object.prototype.attributes = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new reflection.KeyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Object.prototype.attributesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
reflection.Object.prototype.documentation = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
reflection.Object.prototype.documentationLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.Object.startObject = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
reflection.Object.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fieldsOffset
 */
reflection.Object.addFields = function(builder, fieldsOffset) {
  builder.addFieldOffset(1, fieldsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Object.createFieldsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Object.startFieldsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isStruct
 */
reflection.Object.addIsStruct = function(builder, isStruct) {
  builder.addFieldInt8(2, +isStruct, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} minalign
 */
reflection.Object.addMinalign = function(builder, minalign) {
  builder.addFieldInt32(3, minalign, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} bytesize
 */
reflection.Object.addBytesize = function(builder, bytesize) {
  builder.addFieldInt32(4, bytesize, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} attributesOffset
 */
reflection.Object.addAttributes = function(builder, attributesOffset) {
  builder.addFieldOffset(5, attributesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Object.createAttributesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Object.startAttributesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} documentationOffset
 */
reflection.Object.addDocumentation = function(builder, documentationOffset) {
  builder.addFieldOffset(6, documentationOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Object.createDocumentationVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Object.startDocumentationVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.Object.endObject = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  builder.requiredField(offset, 6); // fields
  return offset;
};

/**
 * @constructor
 */
reflection.Schema = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {reflection.Schema}
 */
reflection.Schema.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {reflection.Schema=} obj
 * @returns {reflection.Schema}
 */
reflection.Schema.getRootAsSchema = function(bb, obj) {
  return (obj || new reflection.Schema).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
reflection.Schema.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('BFBS');
};

/**
 * @param {number} index
 * @param {reflection.Object=} obj
 * @returns {reflection.Object}
 */
reflection.Schema.prototype.objects = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new reflection.Object).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Schema.prototype.objectsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {reflection.Enum=} obj
 * @returns {reflection.Enum}
 */
reflection.Schema.prototype.enums = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new reflection.Enum).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
reflection.Schema.prototype.enumsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.Schema.prototype.fileIdent = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
reflection.Schema.prototype.fileExt = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {reflection.Object=} obj
 * @returns {reflection.Object|null}
 */
reflection.Schema.prototype.rootTable = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new reflection.Object).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
reflection.Schema.startSchema = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectsOffset
 */
reflection.Schema.addObjects = function(builder, objectsOffset) {
  builder.addFieldOffset(0, objectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Schema.createObjectsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Schema.startObjectsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} enumsOffset
 */
reflection.Schema.addEnums = function(builder, enumsOffset) {
  builder.addFieldOffset(1, enumsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
reflection.Schema.createEnumsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
reflection.Schema.startEnumsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fileIdentOffset
 */
reflection.Schema.addFileIdent = function(builder, fileIdentOffset) {
  builder.addFieldOffset(2, fileIdentOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} fileExtOffset
 */
reflection.Schema.addFileExt = function(builder, fileExtOffset) {
  builder.addFieldOffset(3, fileExtOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rootTableOffset
 */
reflection.Schema.addRootTable = function(builder, rootTableOffset) {
  builder.addFieldOffset(4, rootTableOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
reflection.Schema.endSchema = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // objects
  builder.requiredField(offset, 6); // enums
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
reflection.Schema.finishSchemaBuffer = function(builder, offset) {
  builder.finish(offset, 'BFBS');
};

// Exports for Node.js and RequireJS
this.reflection = reflection;
